#ifndef RTCW_SYS_RESOURCE_SDL_H
#define RTCW_SYS_RESOURCE_SDL_H

#define IDI_ICON1       1
#define IDS_STRING1     1

#ifndef CREATEPROCESS_MANIFEST_RESOURCE_ID
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#endif

#endif
